version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: myproject-ll-redis

    mysql:
      image: mysql:5.7
      container_name: myproject-ll-mysql
      working_dir: /application
      volumes:
        - .:/application
        - ./src/myproject.ll/_MySQL:/docker-entrypoint-initdb.d
      environment:
        - MYSQL_ROOT_PASSWORD=2Ple86kcJZibGC5y
        - MYSQL_DATABASE=myproject
        - MYSQL_USER=myproject
        - MYSQL_PASSWORD=2Ple86kcJZibGC5y
      ports:
        - "8082:3306"

    webserver:
      image: nginx:alpine
      container_name: myproject-ll-webserver
      working_dir: /application
      links:
       - php-fpm
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./phpdocker/nginx/htpasswd:/etc/nginx/htpasswd
      ports:
       - "8888:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: myproject-ll-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

